version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: clipo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: clipo_ai
  redis:
    image: redis:7.2-alpine
    container_name: clipo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mongodb_data:
  redis_data:
